import test from "node:test";import assert from "node:assert/strict";
import {createIntent,compileIntent,discoverDemand,discoverCapabilities,compareCapabilities,composeSolution,simulate,qualify,authorize,recordOutcome,verifyOutcome,benchmark,learnFromOutcome,createOpportunity,productize,buildWorldPortfolio,closeWorldCycle,assertWorldConstitution} from "../scripts/acorn-universal-world-engine.mjs";
test("constitution is explicit",()=>assert.equal(assertWorldConstitution(),true));
test("intent compiles to tasks",()=>{const x=compileIntent(createIntent({objective:"deliver"}));assert.equal(x.state,"COMPILED");assert.equal(x.tasks.length,0)});
test("empty intent is rejected",()=>assert.equal(compileIntent({}).state,"INVALID"));
test("unknown demand stays exploratory",()=>assert.equal(discoverDemand([{domain:"MARKET",state:"UNKNOWN"}])[0].demand_state,"EXPLORATORY"));
test("unverified capability cannot rank",()=>assert.equal(compareCapabilities([{id:"x",verified:false,evidence:["e"],quality:99}]).length,0));
test("verified capability ranks in scope",()=>assert.equal(compareCapabilities([{id:"x",verified:true,evidence:["e"],quality:99}])[0].selection_state,"BEST_KNOWN_IN_SCOPE"));
test("composition reports gaps",()=>assert.equal(composeSolution([{requirement:"missing"}],[{verified:true,evidence:["e"],capabilities:["other"]}]).state,"GAP_REMAINS"));
test("simulation is never execution",()=>assert.equal(simulate({}).executed,false));
test("qualification is not verification",()=>assert.equal(qualify({state:"COMPOSED"},["e"]).verified,false));
test("consequential effects remain human gated",()=>assert.equal(authorize("MERGE",{human_authorized:true,server_authorized:true}).authorized,false));
test("safe effect needs explicit server and human authorization",()=>assert.equal(authorize("READ",{human_authorized:true,server_authorized:true}).authorized,true));
test("payment does not prove execution",()=>{const o=recordOutcome({payment_observed:true});assert.equal(o.executed,false)});
test("verification needs measured evidence",()=>assert.equal(verifyOutcome({executed:true,measured:false,verified:true,evidence:["e"]}).state,"NOT_VERIFIED"));
test("benchmark is scoped",()=>assert.equal(benchmark([{verified:true,measured:true,score:10}],{scope:"x"}).global_optimum_claim,false));
test("learning rejects unsupported outcome",()=>assert.equal(learnFromOutcome({verified:false,measured:false}).state,"REJECTED"));
test("opportunity requires verified demand and capability",()=>assert.equal(createOpportunity({verified:true},{verified:false}).verified,false));
test("productization requires reusable verified asset",()=>assert.equal(productize({verified:false,reusable:true}).state,"NOT_READY"));
test("portfolio preserves authority boundary",()=>{const p=buildWorldPortfolio({intent:{objective:"x"}});assert.equal(p.authority,"HUMAN_REQUIRED");assert.equal(p.auto_merge,false)});
test("closed cycle creates reusable candidate",()=>{const x=closeWorldCycle({id:"o1",executed:true,measured:true,verified:true,evidence:["e"],demand_verified:true,reusable:true});assert.equal(x.state,"CLOSED_AND_REUSABLE")});
