import test from "node:test"; import assert from "node:assert/strict";
import {createKnowledge,validateKnowledge,shareKnowledge,buildKnowledgeGraph,deriveInsight,routeKnowledge,expireKnowledge,cortexSnapshot,assertCortexConstitution} from "../scripts/acorn-cortex-knowledge-fabric.mjs";
test("knowledge is provenance-first",()=>{const k=createKnowledge({subject:"x",predicate:"works",value:true,source:"test",evidence:["e"],confidence:.9});assert.equal(k.state,"PROVISIONAL");assert.equal(validateKnowledge(k).state,"VERIFIED");});
test("knowledge can circulate without authority",()=>{const k=validateKnowledge(createKnowledge({subject:"x",predicate:"works",value:true,source:"a",evidence:["e"],confidence:.9}));const s=shareKnowledge(k);assert.equal(s.shared,true);assert.equal(s.authority,false);});
test("cortex builds shared graph",()=>{const a=validateKnowledge(createKnowledge({subject:"x",predicate:"p",value:1,source:"a",evidence:["e"],confidence:.8}));const b=validateKnowledge(createKnowledge({subject:"x",predicate:"q",value:2,source:"b",evidence:["e"],confidence:.7}));assert.equal(buildKnowledgeGraph([a,b]).edges.length,1);});
test("insights remain provisional",()=>{const k=validateKnowledge(createKnowledge({subject:"x",predicate:"p",value:1,source:"a",evidence:["e"],confidence:.8}));assert.equal(deriveInsight({knowledge:[k],goal:"g"}).requires_validation,true);});
test("routing prefers confidence",()=>{const a=validateKnowledge(createKnowledge({subject:"x",predicate:"p",value:1,source:"a",evidence:["e"],confidence:.5}));const b=validateKnowledge(createKnowledge({subject:"x",predicate:"p",value:2,source:"b",evidence:["e"],confidence:.9}));assert.equal(routeKnowledge({knowledge:[a,b],need:"x"})[0],b.id);});
test("expired knowledge is excluded",()=>{const k=createKnowledge({subject:"x",predicate:"p",value:1,source:"a",evidence:["e"],expires_at:"2000-01-01T00:00:00Z"});assert.equal(expireKnowledge({knowledge:[k]})[0].state,"EXPIRED");});
test("cortex constitution protects traceability and Breaker",()=>{assert.equal(assertCortexConstitution(),true);assert.throws(()=>assertCortexConstitution({breaker_touched:true}),/BREAKER/);assert.throws(()=>assertCortexConstitution({hidden_learning:true}),/TRACEABLE/);});
