import test from "node:test";
import assert from "node:assert/strict";
import { createConcept, discoverUnknownSpace, classifyUnknown, measureConcept, falsifyConcept, retractConcept, capabilityTrajectory, governability, detectEmergence, selectInformationExperiment, cognitiveEcology, successionEnvelope, runBeyondPlasticityCycle, assertBeyondPlasticityInvariant, VERSION } from "../scripts/acorn-beyond-plasticity.mjs";

test("unknown is a first-class state, not an error",()=>{const x=createConcept({name:"future-thing"});assert.equal(x.state,"UNKNOWN");assert.equal(x.kind,"UNKNOWN_KIND");assert.equal(x.authority_granted,false);});
test("unknown space is discoverable from observations and limits",()=>{const xs=discoverUnknownSpace({observations:[{name:"new-effect"}],limits:[{name:"causal-boundary"}]});assert.equal(xs.length,2);assert.ok(xs.every(x=>x.state==="UNKNOWN"));});
test("unknown classification preserves uncertainty",()=>{const x=classifyUnknown(createConcept({name:"x"}),{testable:true,accessible:false,critical:true});assert.equal(x.state,"UNKNOWN");assert.ok(x.unknown_dimensions.includes("UNKNOWN-BUT-INACCESSIBLE"));});
test("epistemic transitions are explicit",()=>{const x=createConcept({kind:"CAPABILITY",name:"p"});const m=measureConcept(x,{observed:true,confidence:.8,observability:1,controllability:1,reversibility:1});assert.equal(m.state,"OBSERVED");assert.equal(falsifyConcept(m,"contradiction").state,"CONTRADICTED");assert.equal(retractConcept(m,"expired").state,"EXPIRED");});
test("trajectory exposes drift and divergence",()=>{const t=capabilityTrajectory([{confidence:.4,observability:.5,novelty:.2},{confidence:.8,observability:.9,novelty:.8,controllability:.2}]);assert.equal(t.direction,"RISING");assert.ok(t.divergence>.5);});
test("governability never becomes authority",()=>{const x=createConcept({kind:"CAPABILITY",name:"x",observability:1,controllability:1,reversibility:1});const g=governability(x);assert.equal(g.status,"GOVERNABLE");assert.equal(g.authority_granted,false);});
test("emergence is observable without granting authority",()=>{const x=createConcept({kind:"CAPABILITY",name:"new"});const e=detectEmergence({before:[],after:[x]});assert.equal(e.length,1);assert.equal(e[0].emergent,true);assert.equal(e[0].authority_granted,false);});
test("information seeking selects a testable unknown",()=>{const a=createConcept({name:"a",novelty:1,observability:.8,controllability:1,reversibility:1});const b=createConcept({name:"b",novelty:.2,observability:.2});assert.equal(selectInformationExperiment([a,b]).id,a.id);});
test("succession keeps Acorn replaceable and future open",()=>{const s=successionEnvelope();assert.equal(s.instance_replaceable,true);assert.equal(s.model_replaceable,true);assert.equal(s.unknown_future_permitted,true);});
test("full beyond-plasticity cycle is constitutional",()=>{const r=runBeyondPlasticityCycle({concepts:[createConcept({kind:"CAPABILITY",name:"planning",state:"VERIFIED",confidence:.9,observability:1,controllability:1,reversibility:1})],observations:[{name:"new-interaction"}],limits:[{name:"causal-boundary"}]});assert.equal(r.version,VERSION);assert.equal(r.authority,"carl");assert.equal(r.authority_granted,false);assert.equal(r.breaker_bypass,false);assert.equal(r.auto_merge,false);assert.equal(r.live,false);assert.equal(r.succession.unknown_future_permitted,true);assert.equal(assertBeyondPlasticityInvariant(r).status,"VERIFIED");assert.equal(cognitiveEcology({concepts:r.concepts}).open_world,true);});
