import test from "node:test"; import assert from "node:assert/strict";
import {createResource,measureResource,createBudget,assessCapacity,rankResourcePlan,learnResourceEfficiency,optimizeResourceAllocation,buildMetabolismSnapshot,assertMetabolismConstitution} from "../scripts/acorn-cognitive-metabolism-resource-fabric.mjs";
test("contract and typed resource",()=>{const r=createResource({id:"cpu",type:"COMPUTE",amount:10}); assert.equal(r.type,"COMPUTE"); assert.equal(r.authority,false);});
test("measurement preserves evidence boundary",()=>{const r=measureResource(createResource({id:"t",type:"TOKEN",amount:100}),{consumed:30,verified:true}); assert.equal(r.remaining,70); assert.equal(r.measurement.verified,true);});
test("capacity exposes deficits",()=>{const r=createResource({id:"c",type:"COMPUTE",amount:2}); const x=assessCapacity({resources:[r],request:{COMPUTE:5}}); assert.equal(x.feasible,false); assert.equal(x.gaps[0].deficit,3);});
test("resource plans are ranked without authority",()=>{const x=rankResourcePlan({plans:[{id:"a",cost:1,reliability:1,capacity:1,evidence:[1]},{id:"b",cost:9,reliability:.5,capacity:.5,evidence:[]} ]}); assert.equal(x.plans[0].id,"a"); assert.equal(x.authority,false);});
test("learning requires measured verified outcome",()=>{assert.equal(learnResourceEfficiency({baseline:{cost:100},outcome:{cost:50,measured:true,verified:true}}).state,"LEARNED"); assert.equal(learnResourceEfficiency({baseline:{cost:100},outcome:{cost:50,measured:true,verified:false}}).state,"NO_LEARNING");});
test("optimization remains candidate only",()=>{const x=optimizeResourceAllocation({resources:[createResource({id:"c",type:"COMPUTE",amount:5})],requests:[{id:"r",requirements:{COMPUTE:3}}]}); assert.equal(x.allocations[0].capacity,true); assert.equal(x.external_effect,false);});
test("snapshot and constitutional guards",()=>{const s=buildMetabolismSnapshot(); assert.equal(s.authority,false); assert.equal(assertMetabolismConstitution(s),true); assert.throws(()=>assertMetabolismConstitution({auto_spend:true}),/CANNOT_SPEND/);});
