import test from "node:test"; import assert from "node:assert/strict";
import {ingestSignal,contextualize,detectConflicts,routeContext,refreshContext,buildCortexPulse,assertCortexContextConstitution} from "../scripts/acorn-cortex-context-orchestration.mjs";
test("cortex ingests traceable signals",()=>{const s=ingestSignal({type:"NEED",payload:{x:1},source:"human",evidence:["e"],confidence:.9});assert.equal(s.state,"OPEN");assert.equal(s.authority,false);});
test("context aggregates the environment",()=>{const a=ingestSignal({type:"NEED",payload:{x:1},source:"a"});const b=ingestSignal({type:"CAPABILITY",payload:{x:1},source:"b"});const c=contextualize({signals:[a,b],goal:"solve"});assert.equal(c.signals.length,2);});
test("conflicting signals remain visible",()=>{const a=ingestSignal({type:"RISK",payload:{level:"low"},source:"a",confidence:.4});const b=ingestSignal({type:"RISK",payload:{level:"high"},source:"b",confidence:.9});assert.equal(detectConflicts({signals:[a,b]}).length,1);});
test("context routes without authority",()=>{const c=routeContext({context:{goal:"vision reasoning"},capabilities:["vision","reasoning","x"]});assert.deepEqual(c.matching_capabilities,["vision","reasoning"]);assert.equal(c.authority,false);});
test("expired context is explicit",()=>{const s=ingestSignal({type:"EVENT",payload:{x:1},source:"a",expires_at:"2000-01-01T00:00:00Z"});assert.equal(refreshContext({signals:[s]})[0].state,"EXPIRED");});
test("cortex pulse is measurable",()=>{const p=buildCortexPulse({signals:[{}],knowledge:[{},{}],capabilities:[{}]});assert.equal(p.signals,1);assert.equal(p.knowledge,2);});
test("hard boundaries remain immutable",()=>{assert.equal(assertCortexContextConstitution(),true);assert.throws(()=>assertCortexContextConstitution({breaker_touched:true}),/BREAKER/);assert.throws(()=>assertCortexContextConstitution({hidden_context:true}),/TRACEABLE/);assert.throws(()=>assertCortexContextConstitution({authority_transfer:true}),/AUTHORITY/);});
