import test from "node:test";
import assert from "node:assert/strict";
import { createSynapticNode,createSynapse,qualifySynapse,scoreSynapse,routeSynapses,learnSynapse,optimizeSynapticGraph,buildSynapticSnapshot,assertSynapticConstitution,CONTRACT } from "../scripts/acorn-dynamic-synaptic-cognitive-fabric.mjs";
test("contract creates typed nodes and synapses",()=>{const a=createSynapticNode({id:"world",type:"ENTITY"});const b=createSynapticNode({id:"coder",type:"INTELLIGENCE",capabilities:["CODE"]});const s=createSynapse({from:a.id,to:b.id,capability:"CODE",evidence:["e1"],reliability:.9,state:"QUALIFIED"});assert.equal(CONTRACT,"acorn.dynamic-synaptic-cognitive-fabric.v1");assert.equal(s.authority,false);});
test("qualification requires evidence",()=>{const s=createSynapse({from:"a",to:"b",capability:"X"});assert.equal(qualifySynapse(s).state,"PROPOSED");assert.equal(qualifySynapse({...s,evidence:["e"]}).state,"QUALIFIED");});
test("routing is capability-specific and ranked",()=>{const n=[createSynapticNode({id:"a",type:"ENTITY"}),createSynapticNode({id:"b",type:"INTELLIGENCE"}),createSynapticNode({id:"c",type:"INTELLIGENCE"})];const s1=createSynapse({from:"a",to:"b",capability:"CODE",evidence:["e"],reliability:.8,state:"ACTIVE"});const s2=createSynapse({from:"a",to:"c",capability:"CODE",evidence:["e"],reliability:.2,state:"ACTIVE"});const r=routeSynapses({from:"a",required_capability:"CODE",synapses:[s1,s2],nodes:n});assert.equal(r.candidates[0].id,s1.id);});
test("learning changes synaptic weight only from measured verified outcome",()=>{const s=createSynapse({from:"a",to:"b",capability:"X",weight:.5});assert.equal(learnSynapse({synapse:s,outcome:{measured:false,verified:false}}).weight,.48);assert.equal(learnSynapse({synapse:s,outcome:{measured:true,verified:true,valid:true}}).weight,.55);});
test("graph optimization ranks learned routes",()=>{const s=createSynapse({from:"a",to:"b",capability:"X",evidence:["e"],reliability:.9,state:"ACTIVE"});const o=optimizeSynapticGraph({synapses:[s],outcomes:[{synapse_id:s.id,measured:true,verified:true,valid:true}]});assert.equal(o.learning_requires_measured_verified,true);assert.equal(o.synapses[0].weight,.55);});
test("snapshot and constitution preserve boundaries",()=>{const s=createSynapse({from:"a",to:"b",capability:"X"});assert.equal(buildSynapticSnapshot({nodes:[],synapses:[s]}).authority,false);assert.throws(()=>assertSynapticConstitution({authority:true}),/AUTHORITY/);assert.throws(()=>assertSynapticConstitution({breaker_touched:true}),/BREAKER/);assert.throws(()=>assertSynapticConstitution({external_effect:true}),/EXECUTE/);assert.equal(assertSynapticConstitution({}),true);});
