import test from 'node:test';
import assert from 'node:assert/strict';
import { VERSION, createConsequence, consequenceChain, traceabilityGap, causalAssessment, responsibilityEvidence, retractConsequence, runConsequenceLedgerCycle, assertConsequenceLedgerInvariant, assertConsequenceLedgerConstitution } from '../scripts/acorn-cognitive-consequence-ledger.mjs';

test('ledger distinguishes intent, effect and consequence',()=>{const r=createConsequence({identity:'cortex',intent:'plan',action:'execute',effect:'file-change',consequence:'measured-change'});assert.equal(VERSION,'acorn.cortex.cognitive-consequence-ledger.v1');assert.equal(r.intent,'plan');assert.equal(r.effect,'file-change');assert.equal(r.consequence,'measured-change');assert.equal(r.authorityGranted,false);});
test('traceability gap is explicit and fail-closed',()=>{const g=traceabilityGap({identity:'x',action:'a',effect:'e',consequence:'c',evidence:[],observability:'UNKNOWN',control:'UNKNOWN'});assert.equal(g.gap,true);assert.deepEqual(g.missing,['EVIDENCE','OBSERVABILITY','CONTROL']);});
test('causality requires intervention, counterfactual and replication',()=>{const h=causalAssessment({intervention:true,counterfactual:true});assert.equal(h.attribution,'CAUSAL_HYPOTHESIS');const c=causalAssessment({intervention:true,counterfactual:true,replicated:true,independentEvidence:true});assert.equal(c.attribution,'CAUSAL_CONFIRMED');});
test('responsibility evidence never assigns blame or authority',()=>{const r=responsibilityEvidence({actor:'cortex',records:[{state:'VERIFIED',attribution:'CORROBORATED'}],authority:false});assert.equal(r.responsibilityEvidence,true);assert.equal(r.legalOrMoralBlameAssigned,false);assert.equal(r.authorityGranted,false);});
test('retraction preserves history',()=>{const r=retractConsequence(createConsequence({identity:'x',action:'a'}),'CONTRADICTED');assert.equal(r.state,'EXPIRED');assert.equal(r.retracted,true);assert.equal(r.historyPreserved,true);});
test('chain is ordered and evidence-bearing',()=>{const c=consequenceChain([{id:'a',state:'OBSERVED',evidence:['e']}]);assert.equal(c[0].index,0);assert.equal(c[0].relation,'INTENT');assert.equal(c[0].evidenceCount,1);});
test('full cycle preserves constitutional invariants',()=>{const r=runConsequenceLedgerCycle({identity:'cortex',capability:'cap',intent:'plan',action:'execute',effect:'effect',consequence:'consequence',observability:'VERIFIED',control:'VERIFIED',reversibility:'REVERSIBLE',evidence:['obs'],causal:{intervention:true,counterfactual:true,replicated:true,independentEvidence:true}});assertConsequenceLedgerInvariant(r);assert.equal(r.causal.attribution,'CAUSAL_CONFIRMED');});
test('constitution preserves sovereignty boundary',()=>{const c=assertConsequenceLedgerConstitution();assert.equal(c.traceabilityNotAuthority,true);assert.equal(c.provenanceNotBlame,true);assert.equal(c.carlControlsBreaker,true);assert.equal(c.breakerDoesNotControlCarl,true);assert.equal(c.acornControlsNeither,true);});