import test from 'node:test';
import assert from 'node:assert/strict';
import { VERSION, assessAgency, authorityBoundary, effectSurface, agencyGap, autonomyDoesNotGrantAuthority, runAgencyBoundaryCycle, assertAgencyBoundaryInvariant, assertAgencyConstitution } from '../scripts/acorn-agency-boundary.mjs';

test('autonomy, agency, authority and sovereignty remain distinct',()=>{const a=assessAgency({capability:true,intent:true,execution:true,effect:true,observability:'VERIFIED',control:'VERIFIED',reversibility:'REVERSIBLE'});assert.equal(VERSION,'acorn.cortex.agency-boundary.v1');assert.equal(a.authority,false);assert.equal(a.sovereignty,false);assert.equal(a.authorityGranted,false);});
test('Carl-only Breaker boundary is explicit',()=>{const ai=authorityBoundary({actor:'cortex',requestedAuthority:true,breakerState:'RUN'});assert.equal(ai.authorized,false);assert.equal(ai.authorityGranted,false);const carl=authorityBoundary({actor:'carl',requestedAuthority:true,breakerState:'RUN'});assert.equal(carl.authorized,true);});
test('unknown control creates an agency gap',()=>{const g=agencyGap({observability:'UNKNOWN',control:'UNKNOWN',reversibility:'UNKNOWN'});assert.equal(g.gap,true);assert.deepEqual(g.missing,['OBSERVABILITY','CONTROL','REVERSIBILITY']);});
test('effect governance requires observation, control and reversibility',()=>{assert.equal(effectSurface({capability:true,observability:'VERIFIED',control:'VERIFIED',reversibility:'REVERSIBLE'}).governable,true);assert.equal(effectSurface({capability:true}).governable,false);});
test('autonomy never grants authority or sovereignty',()=>{const x=autonomyDoesNotGrantAuthority({autonomy:'AUTONOMOUS'});assert.equal(x.valid,true);assert.equal(x.authorityGranted,false);assert.equal(x.sovereigntyGranted,false);});
test('cycle preserves constitutional invariants',()=>{const r=runAgencyBoundaryCycle({identity:'x',capability:'c',context:'ctx',execution:true,effect:true,observability:'VERIFIED',control:'VERIFIED',reversibility:'REVERSIBLE'});assertAgencyBoundaryInvariant(r);assert.equal(r.authorityGranted,false);assert.equal(r.sovereigntyGranted,false);});
test('constitution preserves Carl/Breaker rule',()=>{const c=assertAgencyConstitution();assert.equal(c.carlControlsBreaker,true);assert.equal(c.breakerDoesNotControlCarl,true);assert.equal(c.acornControlsNeither,true);assert.equal(c.cognitiveSuperiorityNotAuthority,true);});
