import pg from "pg";
import crypto from "node:crypto";
import { customerServiceCycle } from "../scripts/acorn-customer-service.mjs";
import { registerEvidence } from "../scripts/acorn-evidence-registry.mjs";
const {Pool}=pg;if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL_REQUIRED");
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:3,connectionTimeoutMillis:5000,idleTimeoutMillis:30000});const WORKER_ID=process.env.WORKER_ID||("acorn-worker-"+crypto.randomUUID());const POLL_MS=Math.max(250,Number(process.env.WORKER_POLL_MS||1000));const now=()=>new Date().toISOString();let stopping=false;
async function migrate(){await pool.query("CREATE TABLE IF NOT EXISTS acorn_jobs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,kind TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,state TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,max_attempts INTEGER NOT NULL DEFAULT 3,worker_id TEXT,result JSONB,error TEXT,evidence JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,finished_at TIMESTAMPTZ)");await pool.query("CREATE INDEX IF NOT EXISTS idx_acorn_jobs_claim ON acorn_jobs(state,created_at)");await pool.query("ALTER TABLE acorn_evidence ADD COLUMN IF NOT EXISTS tenant_id TEXT");await pool.query("ALTER TABLE acorn_evidence ADD COLUMN IF NOT EXISTS claim TEXT");await pool.query("ALTER TABLE acorn_evidence ADD COLUMN IF NOT EXISTS source TEXT");await pool.query("ALTER TABLE acorn_evidence ADD COLUMN IF NOT EXISTS strength DOUBLE PRECISION DEFAULT 0")}
async function ingest(){await pool.query("INSERT INTO acorn_jobs(id,tenant_id,kind,payload,state,attempts,max_attempts,created_at,updated_at) SELECT 'job_'||r.id,r.customer_id,'CUSTOMER_REQUEST',jsonb_build_object('request_id',r.id),'QUEUED',0,3,r.created_at,r.updated_at FROM requests r LEFT JOIN acorn_jobs j ON j.id='job_'||r.id WHERE j.id IS NULL ON CONFLICT DO NOTHING")}
async function claim(){const c=await pool.connect();try{await c.query("BEGIN");const q=await c.query("SELECT id FROM acorn_jobs WHERE state='QUEUED' AND attempts<max_attempts ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 5");const jobs=[];for(const row of q.rows){const r=await c.query("UPDATE acorn_jobs SET state='RUNNING',worker_id=$1,attempts=attempts+1,updated_at=$2 WHERE id=$3 RETURNING *",[WORKER_ID,now(),row.id]);jobs.push(r.rows[0])}await c.query("COMMIT");return jobs}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
async function execute(job){const requestId=job.payload.request_id;const r=await pool.query("SELECT * FROM requests WHERE id=$1 AND customer_id=$2",[requestId,job.tenant_id]);if(!r.rows[0]){await pool.query("UPDATE acorn_jobs SET state='FAILED',error=$1,updated_at=$2,finished_at=$2 WHERE id=$3",["REQUEST_NOT_FOUND",now(),job.id]);return}try{const body=typeof r.rows[0].body==="string"?JSON.parse(r.rows[0].body):r.rows[0].body;const cycle=customerServiceCycle({customer:{customer_id:job.tenant_id},request:String(body.request||""),capabilities:["general"],solution:"Acorn intake and qualification",deliverables:["qualified request","execution plan"],evidence_plan:["worker execution evidence"],usage_rights:["CUSTOMER_USE_PENDING_HUMAN_AUTHORIZATION"],tasks:["qualify","plan","verify"],intelligence:["acorn"],human_authorized:false});const t=now();const evidence=registerEvidence({tenantId:job.tenant_id,claim:"worker_execution",source:"acorn-live-worker",kind:"OBSERVATION",strength:1,margin:0.1,validUntil:new Date(Date.now()+86400000).toISOString()});await pool.query("UPDATE requests SET status=$1,updated_at=$2 WHERE id=$3 AND customer_id=$4",[cycle.stage,t,requestId,job.tenant_id]);await pool.query("INSERT INTO events(request_id,type,payload,created_at) VALUES($1,$2,$3,$4)",[requestId,"WORKER_EXECUTION_COMPLETED",JSON.stringify({job_id:job.id,worker_id:WORKER_ID,stage:cycle.stage,human_authorized:false,external_effect:false,live:false}),t]);await pool.query("INSERT INTO acorn_evidence(id,tenant_id,request_id,claim,source,kind,status,origin,measured_at,valid_until,strength,margin,confidence,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (id) DO NOTHING",[evidence.id,job.tenant_id,requestId,evidence.claim,evidence.source,evidence.kind,evidence.status,evidence.source,evidence.measured_at,evidence.valid_until,evidence.strength,evidence.margin,evidence.strength,JSON.stringify({job_id:job.id,worker_id:WORKER_ID,stage:cycle.stage,authority:false,external_effect:false,live:false})]);await pool.query("INSERT INTO acorn_state(id,entity,version,state,tenant_id,provenance,data,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET state=$4,data=$7,updated_at=$9",[requestId,"PROJECT",1,cycle.stage,job.tenant_id,"acorn-live-worker",JSON.stringify({request_id:requestId,stage:cycle.stage,delivered:false,live:false}),t,t]);await pool.query("UPDATE acorn_jobs SET state='SUCCEEDED',result=$1,evidence=$2,updated_at=$3,finished_at=$3 WHERE id=$4",[JSON.stringify({stage:cycle.stage,external_effect:false,live:false}),JSON.stringify([{kind:"runtime",claim:"worker_execution",status:evidence.status,measured_at:t,worker_id:WORKER_ID,external_effect:false}]),t,job.id])}catch(e){const t=now(),retry=job.attempts<job.max_attempts;await pool.query("UPDATE acorn_jobs SET state=$1,error=$2,updated_at=$3,finished_at=$4 WHERE id=$5",[retry?"QUEUED":"FAILED",String(e?.message||e),t,retry?null:t,job.id])}}
async function shutdown(){if(stopping)return;stopping=true;try{await pool.query("UPDATE acorn_jobs SET state='QUEUED',worker_id=NULL,updated_at=$1 WHERE state='RUNNING' AND worker_id=$2",[now(),WORKER_ID])}finally{await pool.end();process.exit(0)}}
process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);await migrate();console.log(JSON.stringify({service:"acorn-live-worker",worker_id:WORKER_ID,status:"READY",authority:false,live:false,external_effect:false}));while(!stopping){try{await ingest();for(const j of await claim())if(!stopping)await execute(j)}catch(e){console.error("WORKER_TICK_ERROR")}await new Promise(r=>setTimeout(r,POLL_MS))}
