#!/usr/bin/env node
/** Acorn-side cadence planning. Authorization remains the Global Breaker's role. */
export const ADAPTIVE_CADENCE_VERSION = "adaptive-cadence.v1";
export const CADENCE_LEVELS = Object.freeze([0.25, 0.5, 0.75, 1]);
export const SAFETY_STATES = Object.freeze({ STABLE: "STABLE", UNSTABLE: "UNSTABLE", CRITICAL: "CRITICAL" });
const clamp01 = (value, fallback = 0) => { const n = Number(value); return Number.isFinite(n) ? Math.min(1, Math.max(0, n)) : fallback; };
const nonNegative = (value, fallback = 0) => { const n = Number(value); return Number.isFinite(n) ? Math.max(0, n) : fallback; };
const normalizeBreaker = (value) => { const mode = String(value ?? "OFF").trim().toUpperCase(); return ["RUN", "OFF", "DEBUG"].includes(mode) ? mode : "OFF"; };
export function classifySafety({ anomalyScore = 0, errorRate = 0, breakerMode = "RUN" } = {}) { const mode = normalizeBreaker(breakerMode); const anomaly = clamp01(anomalyScore); const errors = clamp01(errorRate); if (mode === "OFF" || anomaly >= 0.8 || errors >= 0.5) return SAFETY_STATES.CRITICAL; if (mode === "DEBUG" || anomaly >= 0.35 || errors >= 0.15) return SAFETY_STATES.UNSTABLE; return SAFETY_STATES.STABLE; }
export function demandScore({ pendingTasks = 0, activeTasks = 0, queuePressure = 0, latency = 0 } = {}) { const volume = clamp01((nonNegative(pendingTasks) + nonNegative(activeTasks)) / 20); const pressure = clamp01(queuePressure); const latencyScore = clamp01(Number(latency) / 10000); return Number(Math.max(volume, pressure, latencyScore).toFixed(4)); }
export function chooseCadence({ demand = 0, stability = SAFETY_STATES.STABLE, current = 0.25 } = {}) { const d = clamp01(demand); const safety = Object.values(SAFETY_STATES).includes(stability) ? stability : SAFETY_STATES.CRITICAL; const currentLevel = CADENCE_LEVELS.includes(Number(current)) ? Number(current) : 0.25; if (safety === SAFETY_STATES.CRITICAL) return 0.25; if (safety === SAFETY_STATES.UNSTABLE) return Math.min(currentLevel, 0.5); if (d < 0.15) return 0.25; if (d < 0.5) return Math.min(Math.max(currentLevel, 0.25), 0.5); if (d < 0.8) return Math.min(Math.max(currentLevel, 0.5), 0.75); return Math.min(Math.max(currentLevel, 0.75), 1); }
export function planAdaptiveCadence({ demand = {}, safety = {}, currentCadence = 0.25, breaker = "RUN" } = {}) { const demandValue = demandScore(demand); const safetyState = classifySafety({ ...safety, breakerMode: breaker }); const nextCadence = chooseCadence({ demand: demandValue, stability: safetyState, current: currentCadence }); return { version: ADAPTIVE_CADENCE_VERSION, demand_score: demandValue, safety_state: safetyState, current_cadence: CADENCE_LEVELS.includes(Number(currentCadence)) ? Number(currentCadence) : 0.25, next_cadence: nextCadence, reason: safetyState === SAFETY_STATES.CRITICAL ? "SAFETY_PRIORITY" : safetyState === SAFETY_STATES.UNSTABLE ? "STABILITY_PRIORITY" : nextCadence > currentCadence ? "MEASURED_DEMAND_INCREASE" : nextCadence < currentCadence ? "MEASURED_DEMAND_DECREASE" : "UNCHANGED", energy_policy: "MINIMIZE_WITHOUT_SAFETY_LOSS", execution_authorized: normalizeBreaker(breaker) === "RUN" && safetyState !== SAFETY_STATES.CRITICAL, production_write_allowed: false, auto_merge: false, live: false, human_authority: "carl", global_breaker_required: true }; }
